name: Ejecutar pruebas de Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias (si las hay)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No hay requirements.txt"

    - name: Ejecutar pruebas
      run: |
        pytest || python3 -m unittest discover